x

diff --git a/nf-dl b/nf-dl
--- a/nf-dl
+++ b/nf-dl
@@ -1,40 +1,55 @@
 #!/bin/sh
 
-download_dir=$(mktemp -d --suffix=_font)
+download_dir="$(mktemp -d --suffix=_font)"
 install_path="$HOME/.local/share/fonts"
 url='https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest'
 
 trap '' TSTP
 trap "rm -r $download_dir 2>/dev/null; exit 0" HUP INT TERM EXIT PWR QUIT
- 
-curl -Ls "$url" -o $download_dir/content.json || { echo "can not download json"; exit 1; }
 
-tag=$(jq -r '.tag_name' $download_dir/content.json) 
+curl -Ls "$url" \
+	-H "accept-encoding:gzip" \
+	--compressed \
+	-o $download_dir/content.json || {
+	echo "can not download json"
+	exit 1
+}
+
+tag=$(jq -r '.tag_name' $download_dir/content.json)
 fonts=$(jq -r '.assets[] | "\(.size)/\(.name)"' $download_dir/content.json | while IFS= read -r line; do
- printf '%s\t\t' "${line%%/*}" | numfmt --to=iec; echo "${line##*/} "
+	printf '%s\t\t' "${line%%/*}" | numfmt --to=iec
+	echo "${line##*/} "
 done | fzf -m --prompt='choose font: ' | awk '{print $NF}')
 
 [ "$fonts" ] || exit
 
-for font in $fonts; do
-    if ! fc-list -q "$font"; then
-      echo "downloading $font..."
-      download="https://github.com/ryanoasis/nerd-fonts/releases/download/$tag/$font"
-      curl -L --progress-bar $download -o $download_dir/$font || { echo "can not download $font"; continue; }
-      unzip -qqo $download_dir/$font -d $download_dir 
-    else
-      echo "$font already installed"
-    fi
+echo "downloading fonts..."
+printf '%s\n' "$fonts" | while read -r font; do
+	if ! fc-list -q "$font"; then
+		url="https://github.com/ryanoasis/nerd-fonts/releases/download/$tag/$font"
+		printf "url = %s\n" "$url"
+		printf "output = %s\n" "$download_dir/${url##*/}"
+	else
+		echo "$font already installed" >&2
+	fi
+done | curl -Z -L -K - || {
+	echo "cannot download fonts"
+	exit 1
+}
+
+echo "extracting fonts..."
+for i in $download_dir/*.zip; do
+	unzip -qqo $i -d $download_dir
 done
 
 echo "installing fonts..."
 find $download_dir \
-  ! -iname "*compatible*" \
-  ! -iname "LICENSE*" \
-  ! -iname "*.json" \
-  ! -iname "readme*" \
-  ! -iname "*.zip" \
-  -type f -exec cp {} $install_path \;
+	! -iname "*compatible*" \
+	! -iname "LICENSE*" \
+	! -iname "*.json" \
+	! -iname "readme*" \
+	! -iname "*.zip" \
+	-type f -exec cp {} $install_path \;
 
 echo "regenerating cache..."
 fc-cache -f
